# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  
  # Puppet DB - Ubuntu
  config.vm.define "db" do |db|
   db.vm.box = "chono-ubuntu-server-v2"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.89.101"
    db.vm.synced_folder "service/", "/vagrant"
    ####### Install Puppet Agent #######
    db.vm.provision "shell", path: "puppet-agent.sh"

    ####### Provision #######
  db.vm.provision "puppet" do |puppet|
    puppet.module_path = "./site"
   end
  end
  
   # Puppet Web - Ubuntu
   config.vm.define "web" do |web|
    web.vm.box = "chono-ubuntu-server-v2"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.89.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.synced_folder "service/", "/vagrant"
    ####### Install Puppet Agent #######
    web.vm.provision "shell", path: "puppet-agent.sh"

    ####### Provision #######
  web.vm.provision "puppet" do |puppet|
    puppet.module_path = "./site"
   end
  end
  
end
