# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  

  config.vm.define "manager" do |manager|
    manager.vm.box="chono-ubuntu-server-v2"
    manager.vm.hostname = "manager.dob.lab"
    manager.vm.network "private_network", ip: "192.168.89.100"
    manager.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    manager.vm.synced_folder "service/", "/vagrant"
    manager.vm.provision "shell", path: "node1.sh"
  end
end
 
