apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  ports:
  - name: tcp-{{ .Values.port }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
      app: mariadb
