apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      name: tcp-{{ .Values.redis.port }}
  selector:
      app: {{ .Values.redis.name }}
