apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin 
  name: phpmyadmin
spec:
  ports:
  - name: http-80
    port: 8080
    targetPort: 80
  selector:
      app: phpmyadmin
  type: LoadBalancer
